Implementation of task 7
leinaly/test_guru pull request #10
Opened 2020-09-20 14:03 UTC by leinaly

2020-09-20 18:13 UTC, BubuntuClu requested changes

2020-09-20 18:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    Question.create!(question_params)
есл параетры будут неподходящие, то у тебя `create!` вызовет экспешен, а тут у тебя никак не обрабатывается эксепшены. блока `rescue` нет.

надо сначала создать объект и потом проверить удалось ли его сохранить в БД, и в зависимости от этого что-то сказать пользователю

2020-09-20 18:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :init_ex
это кто такой?

2020-09-20 18:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @qs = @test.questions
на имена переменных не надо скупиться, полностью стоит писать

2020-09-20 18:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
test_id тут не надо. используй ассоциации при создании вопросов

2020-09-20 18:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @ex << "Test was not found"
зачем инициализировать это в отдельном действии? оно вообще не нужно. тут рендерить стоит другую страницу, так как это 404, а не страница списка вопросов

2020-09-20 18:13 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    render json: { questions: ts }
тут тесты, а не вопросы

2020-09-20 18:13 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="/tests/:test_id/questions" method="post">
сюда передавай тест из параметров

2020-09-20 18:13 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +  <p>
этот блок не нужен, если будешь использовать ассоциации

2020-09-20 18:13 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
попробуй опцию `shallow: true`

2020-09-20 22:07 UTC, leinaly commented on app/controllers/questions_controller.rb
> +    @ex << "Test was not found"
тут идея была в том чтобы показать ошибки на странице с вопросами 
https://github.com/leinaly/test_guru/pull/10/commits/d2f8e35889588738cafa092e29a039049ed868ab#diff-691d3ec14fbb64c69bea7869649ef1acR6
поэтому я рендерила страницу вопросов

2020-09-21 06:17 UTC, BubuntuClu requested changes

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    msg = "Created!"
бэнг методы не стоит просто так использовать
```
@question = @test.questions.new(question_params)
if @question.save
   render good
else
   render bad
end
```

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body).merge(test_id: @test.id)
`.merge(test_id: @test.id)` это тоже самое что и было, только еще хуже)
ассоциации при создании надо использовать, выше тебе написал код

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find_by(id: params[:id])
если ты будешь делать `find_by`, то твой метод rescue_with_test_not_found никогда не сработает. он как раз ловит эксепшены когда нет записей

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find_by(id: params[:id])
нахождение вопроса тоже стоит вынести в `before_action`. тебе объект вопроса понадобиться во многих экшенах

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    Question.destroy(params[:id])
```
def destroy
  @question.destroy
  render json: { result: "Deleted!"}
end
```

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id]) if params[:test_id].present?
проверка тут не нужна, надо просто правильно описать когда вызывать этот метод в `before_action`. не для всех экшенов

2020-09-21 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      msg = "Not created! Smth goes wrong."
опять же, имена переменных. msg => message

2020-09-21 06:17 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +
много пустых строк лишних

2020-09-21 12:16 UTC, BubuntuClu approved these changes

2020-09-21 12:16 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +
их удалить стоит

2020-11-13 17:14 UTC, merged